## import libraries

In [1]:
import torch

#### transition matrix, T(s, s'), consisting of the probabilities of state s transitioning to state s'.
##### s0 (study) and s1 (sleep)

In [2]:
T = torch.tensor([[0.4,0.6],[0.8,0.2]])

transition probability after k steps.

In [3]:
T_2 = torch.matrix_power(T,2)
T_5 = torch.matrix_power(T,5)
T_10 = torch.matrix_power(T,10)
T_15 = torch.matrix_power(T,15)
T_20 = torch.matrix_power(T,20)

### define the intial distribution of two states

meaning there is a 70% chance that the process starts with study and a 30% chance that it starts with sleep.

In [4]:
v = torch.tensor([[0.7,0.3]])

state distribution after k steps.

In [5]:
v_1 = torch.mm(v,T)
v_2 = torch.mm(v,T_2)
v_5 = torch.mm(v,T_5)
v_10 = torch.mm(v,T_10)
v_15 = torch.mm(v,T_15)
v_20 = torch.mm(v,T_20)

In [6]:
print("Transition probability after 2 steps:\n{}".format(T_2))
print("Transition probability after 5 steps:\n{}".format(T_5))
print("Transition probability after 10 steps:\n{}".format(T_10))
print("Transition probability after 15 steps:\n{}".format(T_15))
print("Transition probability after 20 steps:\n{}".format(T_20))

Transition probability after 2 steps:
tensor([[0.6400, 0.3600],
        [0.4800, 0.5200]])
Transition probability after 5 steps:
tensor([[0.5670, 0.4330],
        [0.5773, 0.4227]])
Transition probability after 10 steps:
tensor([[0.5715, 0.4285],
        [0.5714, 0.4286]])
Transition probability after 15 steps:
tensor([[0.5714, 0.4286],
        [0.5714, 0.4286]])
Transition probability after 20 steps:
tensor([[0.5714, 0.4286],
        [0.5714, 0.4286]])


In [7]:
print("Distribution of states after 1 step:\n{}".format(v_1))
print("Distribution of states after 1 step:\n{}".format(v_2))
print("Distribution of states after 1 step:\n{}".format(v_5))
print("Distribution of states after 1 step:\n{}".format(v_10))
print("Distribution of states after 1 step:\n{}".format(v_15))
print("Distribution of states after 1 step:\n{}".format(v_20))

Distribution of states after 1 step:
tensor([[0.5200, 0.4800]])
Distribution of states after 1 step:
tensor([[0.5920, 0.4080]])
Distribution of states after 1 step:
tensor([[0.5701, 0.4299]])
Distribution of states after 1 step:
tensor([[0.5714, 0.4286]])
Distribution of states after 1 step:
tensor([[0.5714, 0.4286]])
Distribution of states after 1 step:
tensor([[0.5714, 0.4286]])
